### ISSUE TITLE
Post link in Atom is incorrect

### ISSUE THREAD

**Issue by gennyble** [duckinator/news.do1g.com#2]
The entry's `<link>` has a URL that does not match the filename. I thought it might be due to the replace in the filename here, [build.py Line 148](https://github.com/duckinator/news.do1g.com/blob/c4a47d9502dbed51d83655f4e81bf6ae79062fbb/build.py#L148), but on further thought that probably doesn't explain the 12-hour time/24-hour time difference.

**Comment by duckinator** [comment]
Looking into this a bit...

```
https://notes.do1g.com/2024-01-19_19.50.09/    (actual URL)
https://news.do1g.com/2024-01-19-07:50PM       (URL in Atom feed)
                      2024-01-19_19.50.09.html (filename)
```

**Comment by duckinator** [comment]
Okay, I figured it out.

The Atom feed is using:

```
https://news.do1g.com/{{ datetime | datetime-to-slug }}
```

The HTML preview is getting the correct URL by using:

```
/{{ filename }}/
```

So in theory I can have the Atom feed use `https://notes.do1g.com/{{ filename }}` and it should work.

**Comment by duckinator** [comment]
Okay, everything has fixed links, now. My attempt to propagate fixes to older posts didn't work with my Atom client, however. 🙁

**Comment by duckinator** [comment]
Thanks for reporting this @gennyble. It should be fixed now, but you may need to re-add my Atom feed for old links to get updated. (I can't find a way to make, or even _suggest_, feed readers update old posts...) ❤️
